apiVersion: v1
entries:
  gatekeeper:
  - apiVersion: v2
    appVersion: v3.13.0-beta.0
    created: "2024-10-15T13:38:17.668096192Z"
    description: A Helm chart for Gatekeeper
    digest: 9525f2e9fd69a2e907086e6650fa5251c589aeff0402035153819a722683223c
    home: https://github.com/open-policy-agent/gatekeeper
    icon: https://open-policy-agent.github.io/gatekeeper/website/img/logo.svg
    keywords:
    - open policy agent
    name: gatekeeper
    sources:
    - https://github.com/open-policy-agent/gatekeeper.git
    urls:
    - https://MayhemYDG.github.io/repo-0/charts/gatekeeper-3.13.0-beta.0.tgz
    version: 3.13.0-beta.0
generated: "2024-10-15T13:38:17.665653055Z"
